name: Docker Bild Photo.Api

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Build coffeepeek.photo.api Docker image
        run: docker build -t winststreloc/coffeepeek.photo.api:latest -f CoffeePeek.Photo.Api/Dockerfile .

      - name: Push coffeepeek.photo.api Docker image
        run: docker push winststreloc/coffeepeek.photo.api:latest
